### ISSUE TITLE
Small problem in MulAdd

### ISSUE THREAD

**Issue by Pigrecos** [joaopauloschuler/neural-api#18]
If I run the XorAndOr example in delphi (or by disabling AVX support in Lazaurus) I get errors while calculating the output of the last layer.

TVolume.MulAdd procedures (Value: T; Original: TVolume);
begin
   {$ IFDEF Debug}
   if Original.Size <> Self.Size then
     raise Exception.Create ('Sizes don''t match at MulAdd:' +
       IntToStr (Self.Size) + 'and' + IntToStr (Original.Size) + '.');
   {$ ENDIF}
   MulAdd (Value, Addr (Original.FData [0]));
end;

Throws the exception which is not the case with AVX.

thank you

**Comment by joaopauloschuler** [comment]
Backpropagation was trying to calculate errors for the input layer (this was the cause of the problem). Please let me know if this fix works at your end. Thank you very much for reporting!

**Comment by Pigrecos** [comment]
now works very well. Thank you
