### ISSUE TITLE
Delphi Swap Endian

### ISSUE THREAD

**Issue by Pigrecos** [joaopauloschuler/neural-api#19]
There is a small error in the delphi function

I corrected it like this:

{$IFNDEF FPC}
function SwapEndian(I:integer):integer;
begin
  // valid for SmallInt
  // result := Swap(I)
  Result := ((Swap(Smallint(I)) and $ffff) shl $10) or (Swap(Smallint(I shr $10)) and $ffff)
end;
{$ENDIF} 

https://github.com/Pigrecos/neural-api/blob/fa2c0f180a1fd2ce239f908cb7419e8c21380676/neural/neuraldatasets.pas#L217

**Comment by joaopauloschuler** [comment]
Thank you for reporting.  Has your fix been tested with 32 or 64 bits?

**Comment by Pigrecos** [comment]
I tested on x32 and x64 and everything is ok.

**Comment by joaopauloschuler** [comment]
If you merge most recent commits into your fork and if all is good, maybe the best path is me merging back your changes.

**Comment by joaopauloschuler** [comment]
Solved with most recent merge. Thank you.
