### ISSUE TITLE
I found some issues

### ISSUE THREAD

**Issue by dinmil** [joaopauloschuler/neural-api#22]
When you try to save neural net settings in string then first float variable is encoded with "," separator, while all others are encoded with ".". This is the is issue with fformatsettings.
Check this sample TNNetFullConnectReLU:4;1;1;0;0;0;0;0>!0,055678159]1;93;1;1;-0.009392704815;-0.06912346184;-0.01935156807;-0.1705754697;

Number 0,055678159 is encoded with colon if you have central european default decimal settings.
So if one computer learn and save result and it is with ',', and the other use that result and it is in US settings (decimal separator i '.') then you will get error while trying to decode this string.

File is TNNetNeuron.LoadFromString. Search for string FBiasWeight := StrToFloat(S[0]) around line 9322. Also check TNNetNeuron.SaveToString(): FloatToStr in same file.

Next issue is 
procedure TNeuralDataLoadingFit.FitLoading(pNN: TNNet; TrainingCnt,

Line   if Assigned(FThreadNN) then FThreadNN.Free;

is this line exists then 

instead of   FThreadNN.Free; in line 604
there should be   FreeAndNil(FThreadNN);

Issue is visible when you try to run FitLoading for the second time.
First time does not have pointer to thread, second time it thinks then it have pointer but it is actually not available because of FThreadNN.Free

Regards, Dinko

**Comment by joaopauloschuler** [comment]
Hello Dinko,
First of all, many thanks for reporting these bugs with so many details! As we are heading towards version 1.0, this is the proper moment for reporting bugs.

In regards to your first bug report, I believe that this is solved on the latest commit at
TNeuralDataLoadingFit.FreeMemory();

In regards to your second bug (encoded with colon), this will be reviewed.

Please feel free to report more problems if you find.

Kind regards.

**Comment by joaopauloschuler** [comment]
Please let me know if this experimental fix solves the problem.

**Comment by dinmil** [comment]
Exprimetal fix is OK for future, but is it problematic for backward compatibility. I use my own fix for that:
function TNNetNeuron.TryToFloat(InString: String): Single;
var MyResult: Single;
begin
  MyResult := 0;
  try
    MyResult := StrToFloat(InString);
  except
    try
      MyResult := StrToFloat(StringReplace(InString, '.', ',', [rfReplaceAll]));
    except
      try
        MyResult := StrToFloat(StringReplace(InString, ',', '.', [rfReplaceAll]));
      except
      end;
    end;
  end;
  Result := MyResult
end;

**Comment by joaopauloschuler** [comment]
Thank you for sharing.
