### ISSUE TITLE
SuperResolution Questions

### ISSUE THREAD

**Issue by jdelauney** [joaopauloschuler/neural-api#26]
Hi, i've just tried your latest example "SuperResolution" with the default training sample file

I've made a little project with Lazarus 2.08/fpc 3.2 under windows 10 64bits for comparing results 
(with my own library for image processing [BZScene](https://github.com/jdelauney/BZScene) )
The code is exaclty the same as your superresolution example.
 
The image is resized with a factor of x2 
a few image is resized perfectly but some others not. 
See attached screenshots

On left the image source not resized, not cropped
On center the image resize with Lanczsos3 resample filter
An on the right the image resized with the NN

(right click and open in new tab for see in full resolution)

- 1st sample : source resolution is 300x300
![Sample1](https://images2.imgbox.com/5c/f8/NejCfl9r_o.jpg)

- 2nd : source  resolution 215x198
![Sample2](https://images2.imgbox.com/43/6a/6Oo5qJUO_o.jpg)

- 3rd : source  resolution 256x256
![Sample3](https://images2.imgbox.com/be/fb/TCRj2XgR_o.jpg)

4th : source  resolution  380x300
![Sample4](https://images2.imgbox.com/ad/9b/FxZCM5lU_o.jpg)

5th : source  resolution  425x425
![Sample5](https://images2.imgbox.com/ac/f2/KkayRdvY_o.jpg)

6th : source  resolution  400x306
![Sample6](https://images2.imgbox.com/af/c3/dkeBwkMY_o.jpg)

So do you think is due to the training ? it is not enougth ? or this provide from an other issue ?

Thanks

BTW your library is awesome, i love it 👍 

Best regards

**Comment by joaopauloschuler** [comment]
Hello jdelauney!
Thank you for your fantastic bug report! Loved looking at it. I've just given a start to your project.

Are you able to send me please one of the images that failed with NN? If yes, I'll debug from my end. I don't think that the problem is training related.

**Comment by jdelauney** [comment]
Hi, Joao
  
  after some little investigations, i found the problem, it's a problem with memory adress assignement by using our two library. I'm explain, when i'm accessing to the pixels of my bitmap with direct pointer like this : 
```
type
  TBZBitmapTransformationsHelper = Class helper for TBZBitmapTransformations
  public
    procedure NeuralResizeTo(DestBmp : TBZBitmap; Const ScaleFactor : Byte);
  end; 

procedure TBZBitmapTransformationsHelper.NeuralResizeTo(DestBmp : TBZBitmap; const ScaleFactor : Byte);
var
  nw, nh : Integer;
var
  NN: TNNet;
  InputImgVol, AuxInputImgVol, OutputImgVol: TNNetVolume;
  InputTile, OutputTile: TNNetVolume;
  MaxTileX, MaxTileY: integer;
  TileXCnt, TileYCnt: integer;
  TileStartX, TileStartY: integer;                      
 
procedure LoadBitmapIntoVolume(M: TBZBitmap; Vol:TNNetVolume);
  var
    CountX, CountY : integer;
    PixelPtr : PBZColor;
    inColor : TBZColor;
    RawPos: integer;
  begin
    Vol.ReSize(M.Width, M.Height, 3);
    PixelPtr := M.GetScanLine(0);
    for CountX := 0 to M.MaxWidth do
    begin
      for CountY := 0 to M.MaxHeight do
      begin
        RawPos := Vol.GetRawPos(CountX, CountY, 0);

        inColor := PixelPtr^; 
       //inColor := M.getPixel(CountX, CountY);
        Vol.FData[RawPos]     := inColor.red;
        Vol.FData[RawPos + 1] := inColor.green;
        Vol.FData[RawPos + 2] := inColor.blue;
        inc(PixelPtr);
      end;
    end;
  end;

  procedure LoadVolumeIntoBitmap(Vol:TNNetVolume; M: TBZBitmap);
  var
    CountX, CountY, MaxX, MaxY: integer;
    PixelPtr: PBZColor;
    OutColor : TBZColor;
    RawPos: integer;
  begin
    MaxX := Vol.SizeX - 1;
    MaxY := Vol.SizeY - 1;
    WriteLn('Resizing output bitmap to: ', Vol.SizeX,' x ', Vol.SizeY);
    M.SetSize(Vol.SizeX, Vol.SizeY);
    PixelPtr := M.GetScanLine(0);
    for CountY := 0 to MaxY do
    begin      
      for CountX := 0 to MaxX do
      begin
        RawPos := Vol.GetRawPos(CountX, CountY, 0);
        OutColor.Create(NeuronForceMinMax(Round(Vol.FData[RawPos]),0,255),
                        NeuronForceMinMax(Round(Vol.FData[RawPos + 1]),0,255),
                        NeuronForceMinMax(Round(Vol.FData[RawPos + 2]),0, 255));
                        
        PixelPtr^ := OutColor;
        //M.setPixel(CountX, CountY, OutColor);
        Inc(PixelPtr);
      end;
    end;
  end;    

begin
  //...
end;         
```
and by calling my resample method before or after neural resize method the probelms appears. 
By using internal methods instead (the commented lines) the problems disapears and all work like expected

![Sample1](https://images2.imgbox.com/58/7e/xhqffvGT_o.jpg)

I don't say why this behaviour appear (with and without the use of AVX). 
It is beacause they are nesteed methods ??? hum i'm using similar methods in other place and it's work 
or because is in an Helper ??? or something else related to fpc 3.2.0 ????
BTW, I'll try others ways later and also with fpc 3.0.4 for see.

Just a little thing with neural resize. The output size, sometime is not right. see screenshots : 

This is ok : 
![Sample2](https://images2.imgbox.com/d3/2f/l54qL8W3_o.jpg)

Those are not ok, the result is cropped
![sample3](https://images2.imgbox.com/af/e5/QZOtkFWj_o.jpg)

Like you see in this last screenshot, output dimensions are wrong, normally it should be 400x400
![sample4](https://images2.imgbox.com/01/a4/XyciQFDu_o.jpg)

Best regards

Jérôme

**Comment by joaopauloschuler** [comment]
Fantastic experiments!

The tiling algorithm can be improved. You are finding cropped images as a result of the tiling algorithm. I'll improve it eventually.

**Comment by joaopauloschuler** [comment]
Problem hasn't been totally solved yet. But it should work on most images.

**Comment by joaopauloschuler** [comment]
Hi Jérôme - I'm curious... Do you have an url where you are integrating this code?

**Comment by jdelauney** [comment]
Hi Joao, yes the code will be available in my next update of my project,
I've tested your changes all seems work as expected. Just one thing, i have a range check error (code error 201) in TNNetPoolBase.SetPrevLayer(pPrevLayer: TNNetLayer);  in neuralnetwork unit.

```
if ((FStride = FPoolSize) and (FPadding = 0)) then
  begin
    MaxInputDivPool := Max(pPrevLayer.Output.SizeX, pPrevLayer.Output.SizeY);// + 1;
    SetLength(FInputDivPool, MaxInputDivPool);
    for MaxInputDivPoolCnt := 0 to MaxInputDivPool-1
      do FInputDivPool[MaxInputDivPoolCnt] := MaxInputDivPoolCnt div FPoolSize;
  end;    
```
By adding 1 to MaxInputDivPool it's ok so i think the problem come from "pPrevLayer.Output.Size?"

Best regards

**Comment by joaopauloschuler** [comment]
Are you able to send me please a step by step to reproduce the range check error? I tried to reproduce it at my end with no luck.

**Comment by jdelauney** [comment]
This bug is incomprehensible it comes from the max function of the math unit of fpc
It's really very weird the returned value does not correspond to anything
See the screenshot : 

![bugreport1](https://images2.imgbox.com/7e/bf/Ix9s89FF_o.jpg)
![bugreport2](https://images2.imgbox.com/02/78/17ueWh9e_o.jpg)
![bugreport3](https://images2.imgbox.com/e0/0d/5bviR31o_o.jpg);

so i've decided to just replace the max function by a simple if..then

```
procedure TNNetPoolBase.SetPrevLayer(pPrevLayer: TNNetLayer);
var
  MaxInputDivPool, MaxInputDivPoolCnt: integer;
begin
  inherited SetPrevLayer(pPrevLayer);
  FOutputSizeX := CalcOutputSize(pPrevLayer.Output.SizeX);
  FOutputSizeY := CalcOutputSize(pPrevLayer.Output.SizeY);
  FOutputSizeD := pPrevLayer.Output.Depth;

  FOutput.ReSize(FOutputSizeX, FOutputSizeY, FOutputSizeD);
  FOutputError.ReSize(FOutputSizeX, FOutputSizeY, FOutputSizeD);
  FOutputErrorDeriv.ReSize(FOutputSizeX, FOutputSizeY, FOutputSizeD);
  SetLength(FMaxPosX, FOutput.Size);
  SetLength(FMaxPosY, FOutput.Size);
  if ((FStride = FPoolSize) and (FPadding = 0)) then
  begin
    Writeln('prev output size X :', pPrevLayer.Output.SizeX);
    Writeln('prev output size Y :', pPrevLayer.Output.SizeY);

    if (pPrevLayer.Output.SizeX >= pPrevLayer.Output.SizeY) then
      MaxInputDivPool := pPrevLayer.Output.SizeX
    else
      MaxInputDivPool := pPrevLayer.Output.SizeY;

    //MaxInputDivPool := Max(pPrevLayer.Output.SizeX, pPrevLayer.Output.SizeY);// + 1;
    SetLength(FInputDivPool, MaxInputDivPool);
    Writeln('PoolSize :', FPoolSize);
    Writeln('MaxInputDivPool : ', MaxInputDivPool);
    for MaxInputDivPoolCnt := 0 to MaxInputDivPool-1 do
    begin
      Writeln('Count : ', MaxInputDivPoolCnt);

      FInputDivPool[MaxInputDivPoolCnt] := MaxInputDivPoolCnt div FPoolSize;
    end;
  end;
end;              
```
And it work as expected. I don't understand why this error occur. I'm using Lazarus 2.08 with FPC 3.2 so it will be possible the bugs come from here. The function is inlined so i think of a memory adressing error. I'll try tomorrow with Lazarus 2.08 and fpc 3.0.4

**Comment by jdelauney** [comment]
Hi Joao, i've tested with Lazarus 2.08 and FPC 3.0.4 the problem not appear. So the bug come from FPC 3.2

**Comment by joaopauloschuler** [comment]
Just gave a go with FPC 3.2 and it works for me. I wounder if this has to do with processor's instruction set. If you put your code in a public repository, I can give a go with your code.

**Comment by jdelauney** [comment]
Do not worry about that, my FPC version is not up to date. The main goal is this is work with FPC 3.0.4 without any problems. I'll update my repository soon i need to do somethings yet.
