### ISSUE TITLE
Errors with Delphi 10 compilation

### ISSUE THREAD

**Issue by JeanYvesJonet** [joaopauloschuler/neural-api#32]
Hello,
when i compile, i have some errors.
Library Neuralopencl, some errors with type, "t" missing , example : "cl_int" unknown, "tcl_int" is OK.
Library Neuraldatasetsv, function "RGB" is unknown, "Uses Windows" is missing at the top of code.
Library Neuralnetwork, function LocalAddBottleNeck,  "UnitCnt+=1" is only for C++ not for Delphi, replaced by inc(UnitCnt)
Thank you very much for your work.
JY

**Comment by joaopauloschuler** [comment]
Thank you for reporting!
