### ISSUE TITLE
Errors build with last release by delphi 10.3 

### ISSUE THREAD

**Issue by JeanYvesJonet** [joaopauloschuler/neural-api#39]
Hello,
lot's of errors during build with Delphi10.3 : 
[dcc32 Erreur] neuralnetwork.pas(756): E2267 La déclaration précédente de 'Create' n'a pas été marquée de la directive 'overload'
[dcc32 Avertissement] neuralnetwork.pas(778): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetFullConnect'
[dcc32 Erreur] neuralnetwork.pas(778): E2267 La déclaration précédente de 'Create' n'a pas été marquée de la directive 'overload'
[dcc32 Avertissement] neuralnetwork.pas(785): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetFullConnect'
[dcc32 Erreur] neuralnetwork.pas(785): E2267 La déclaration précédente de 'Create' n'a pas été marquée de la directive 'overload'
[dcc32 Avertissement] neuralnetwork.pas(796): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetFullConnectLinear'
[dcc32 Erreur] neuralnetwork.pas(796): E2267 La déclaration précédente de 'Create' n'a pas été marquée de la directive 'overload'
[dcc32 Avertissement] neuralnetwork.pas(805): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetFullConnectReLU'
[dcc32 Erreur] neuralnetwork.pas(805): E2267 La déclaration précédente de 'Create' n'a pas été marquée de la directive 'overload'
[dcc32 Avertissement] neuralnetwork.pas(841): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayerConcatedWeights'
[dcc32 Erreur] neuralnetwork.pas(857): E2169 Définition de champ non autorisée après des méthodes ou propriétés
[dcc32 Erreur] neuralnetwork.pas(858): E2070 Directive inconnue : 'Compute'
[dcc32 Erreur] neuralnetwork.pas(858): E2029 ',' ou ':' attendu(e) mais ';' trouvé(e)
[dcc32 Erreur] neuralnetwork.pas(859): E2070 Directive inconnue : 'Backpropagate'
[dcc32 Erreur] neuralnetwork.pas(859): E2029 ';' attendu(e) mais '(' trouvé(e)
[dcc32 Erreur] neuralnetwork.pas(859): E2029 ',' ou ':' attendu(e) mais ';' trouvé(e)
[dcc32 Erreur] neuralnetwork.pas(860): E2070 Directive inconnue : 'InitDefault'
[dcc32 Erreur] neuralnetwork.pas(860): E2029 ';' attendu(e) mais '(' trouvé(e)
[dcc32 Erreur] neuralnetwork.pas(860): E2029 ',' ou ':' attendu(e) mais ';' trouvé(e)
[dcc32 Erreur] neuralnetwork.pas(861): E2029 Type attendu(e) mais 'END' trouvé(e)
[dcc32 Erreur] neuralnetwork.pas(891): E2169 Définition de champ non autorisée après des méthodes ou propriétés
[dcc32 Erreur] neuralnetwork.pas(892): E2029 Type attendu(e) mais 'DESTRUCTOR' trouvé(e)
[dcc32 Avertissement] neuralnetwork.pas(937): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetConvolutionBase'
[dcc32 Erreur] neuralnetwork.pas(937): E2169 Définition de champ non autorisée après des méthodes ou propriétés
[dcc32 Erreur] neuralnetwork.pas(938): E2029 Type attendu(e) mais 'DESTRUCTOR' trouvé(e)
[dcc32 Avertissement] neuralnetwork.pas(956): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetConvolutionBase'
[dcc32 Avertissement] neuralnetwork.pas(962): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetConvolutionLinear'
[dcc32 Avertissement] neuralnetwork.pas(968): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetConvolutionReLU'
[dcc32 Avertissement] neuralnetwork.pas(974): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetConvolutionBase'
[dcc32 Avertissement] neuralnetwork.pas(980): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetConvolutionReLU'
[dcc32 Avertissement] neuralnetwork.pas(1011): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetConvolutionBase'
[dcc32 Avertissement] neuralnetwork.pas(1023): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLocalConnectReLU'
[dcc32 Avertissement] neuralnetwork.pas(1041): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayer'
[dcc32 Erreur] neuralnetwork.pas(2873): E2003 Identificateur non déclaré : 'Compute'
[dcc32 Erreur] neuralnetwork.pas(2877): E2003 Identificateur non déclaré : 'FNeurons'
[dcc32 Erreur] neuralnetwork.pas(2880): E2003 Identificateur non déclaré : 'RefreshCalculatePrevLayerError'
[dcc32 Erreur] neuralnetwork.pas(2881): E2003 Identificateur non déclaré : 'FPadding'
[dcc32 Avertissement] neuralnetwork.pas(2882): W1023 Comparaison de types signés et non signés - opérandes élargis
[dcc32 Erreur] neuralnetwork.pas(2882): E2003 Identificateur non déclaré : 'FInputCopy'
[dcc32 Erreur] neuralnetwork.pas(2882): E2066 Opérateur ou point-virgule manquant
[dcc32 Erreur] neuralnetwork.pas(2882): E2003 Identificateur non déclaré : 'FPrevLayer'
[dcc32 Erreur] neuralnetwork.pas(2882): E2066 Opérateur ou point-virgule manquant
[dcc32 Erreur] neuralnetwork.pas(2890): E2029 ';' attendu(e) mais 'ELSE' trouvé(e)
[dcc32 Erreur] neuralnetwork.pas(2892): E2003 Identificateur non déclaré : 'FErrorProc'
[dcc32 Erreur] neuralnetwork.pas(2892): E2003 Identificateur non déclaré : 'FNeurons'
[dcc32 Erreur] neuralnetwork.pas(2892): E2029 'END' attendu(e) mais ')' trouvé(e)
[dcc32 Erreur] neuralnetwork.pas(2893): E2029 '.' attendu(e) mais ';' trouvé(e)
[dcc32 Avertissement] neuralnetwork.pas(2894): W1011 Texte après le 'END' final. - ignoré par le compilateur
[dcc32 Erreur] neuralnetwork.pas(106): E2065 Déclaration forward ou external non satisfaite : 'TNNetNeuron.Create'
[dcc32 Erreur] neuralnetwork.pas(107): E2065 Déclaration forward ou external non satisfaite : 'TNNetNeuron.Destroy'
[dcc32 Erreur] neuralnetwork.pas(108): E2065 Déclaration forward ou external non satisfaite : 'TNNetNeuron.Fill'
[dcc32 Erreur] neuralnetwork.pas(109): E2065 Déclaration forward ou external non satisfaite : 'TNNetNeuron.AddInertia'
[dcc32 Erreur] neuralnetwork.pas(110): E2065 Déclaration forward ou external non satisfaite : 'TNNetNeuron.UpdateWeights'
[dcc32 Erreur] neuralnetwork.pas(111): E2065 Déclaration forward ou external non satisfaite : 'TNNetNeuron.SaveToString'
[dcc32 Erreur] neuralnetwork.pas(112): E2065 Déclaration forward ou external non satisfaite : 'TNNetNeuron.LoadFromString'
[dcc32 Erreur] neuralnetwork.pas(113): E2065 Déclaration forward ou external non satisfaite : 'TNNetNeuron.ClearDelta'
[dcc32 Erreur] neuralnetwork.pas(116): E2065 Déclaration forward ou external non satisfaite : 'TNNetNeuron.InitUniform'
[dcc32 Erreur] neuralnetwork.pas(117): E2065 Déclaration forward ou external non satisfaite : 'TNNetNeuron.InitGaussian'
[dcc32 Erreur] neuralnetwork.pas(118): E2065 Déclaration forward ou external non satisfaite : 'TNNetNeuron.InitLeCunUniform'
[dcc32 Erreur] neuralnetwork.pas(119): E2065 Déclaration forward ou external non satisfaite : 'TNNetNeuron.InitHeUniform'
[dcc32 Erreur] neuralnetwork.pas(120): E2065 Déclaration forward ou external non satisfaite : 'TNNetNeuron.InitHeGaussian'
[dcc32 Erreur] neuralnetwork.pas(121): E2065 Déclaration forward ou external non satisfaite : 'TNNetNeuron.InitHeUniformDepthwise'
[dcc32 Erreur] neuralnetwork.pas(122): E2065 Déclaration forward ou external non satisfaite : 'TNNetNeuron.InitHeGaussianDepthwise'
[dcc32 Erreur] neuralnetwork.pas(123): E2065 Déclaration forward ou external non satisfaite : 'TNNetNeuron.InitSELU'
[dcc32 Erreur] neuralnetwork.pas(136): E2065 Déclaration forward ou external non satisfaite : 'TNNetNeuronList.GetItem'
[dcc32 Erreur] neuralnetwork.pas(137): E2065 Déclaration forward ou external non satisfaite : 'TNNetNeuronList.SetItem'
[dcc32 Erreur] neuralnetwork.pas(180): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.InitStruct'
[dcc32 Erreur] neuralnetwork.pas(190): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.ComputeL2Decay'
[dcc32 Erreur] neuralnetwork.pas(191): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.ComputePreviousLayerError'
[dcc32 Erreur] neuralnetwork.pas(192): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.SetPrevLayer'
[dcc32 Erreur] neuralnetwork.pas(193): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.ApplyActivationFunctionToOutput'
[dcc32 Erreur] neuralnetwork.pas(194): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.BuildArrNeurons'
[dcc32 Erreur] neuralnetwork.pas(195): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.AfterWeightUpdate'
[dcc32 Erreur] neuralnetwork.pas(197): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.Create'
[dcc32 Erreur] neuralnetwork.pas(198): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.Destroy'
[dcc32 Erreur] neuralnetwork.pas(206): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.ComputeOutputErrorForOneNeuron'
[dcc32 Erreur] neuralnetwork.pas(207): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.ComputeOutputErrorWith'
[dcc32 Erreur] neuralnetwork.pas(208): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.ComputeOutputErrorForIdx'
[dcc32 Erreur] neuralnetwork.pas(209): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.ComputeErrorDeriv'
[dcc32 Erreur] neuralnetwork.pas(210): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.Fill'
[dcc32 Erreur] neuralnetwork.pas(211): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.ClearDeltas'
[dcc32 Erreur] neuralnetwork.pas(212): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.AddNeurons'
[dcc32 Erreur] neuralnetwork.pas(213): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.AddMissingNeurons'
[dcc32 Erreur] neuralnetwork.pas(214): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.SetNumWeightsForAllNeurons'
[dcc32 Erreur] neuralnetwork.pas(215): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.SetNumWeightsForAllNeurons'
[dcc32 Erreur] neuralnetwork.pas(216): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.SetNumWeightsForAllNeurons'
[dcc32 Erreur] neuralnetwork.pas(217): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.GetMaxWeight'
[dcc32 Erreur] neuralnetwork.pas(218): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.GetMinWeight'
[dcc32 Erreur] neuralnetwork.pas(219): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.GetMaxDelta'
[dcc32 Erreur] neuralnetwork.pas(220): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.GetMinDelta'
[dcc32 Erreur] neuralnetwork.pas(221): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.ForceMaxAbsoluteDelta'
[dcc32 Erreur] neuralnetwork.pas(222): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.GetMaxAbsoluteDelta'
[dcc32 Erreur] neuralnetwork.pas(223): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.GetMinMaxAtDepth'
[dcc32 Erreur] neuralnetwork.pas(224): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.GetWeightSum'
[dcc32 Erreur] neuralnetwork.pas(225): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.GetBiasSum'
[dcc32 Erreur] neuralnetwork.pas(226): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.GetInertiaSum'
[dcc32 Erreur] neuralnetwork.pas(227): E2065 Déclaration forward ou external non satisfaite : 'TNNetLayer.CountWeights'
[dcc32 Erreur fatale] neuralnetwork.pas(228): E2226 Compilation abandonnée ; trop d'erreurs

**Comment by HuguesDug** [comment]
Hello,

Here is what to be changed in the neuralnetwork.pas file to get it working.

**Line 755 :**
constructor Create(pSizeX, pSizeY, pDepth: integer; pSuppressBias: integer = 0); virtual;
to be changed by
constructor Create(pSizeX, pSizeY, pDepth: integer; pSuppressBias: integer = 0); overload; virtual;
Overload was missing.

**Line 857:**
    constructor Create(pMultiplier, pFeatureSize, pInputPadding, pStride: integer); virtual; overload;
to be changed by
    constructor Create(pMultiplier, pFeatureSize, pInputPadding, pStride: integer); overload; virtual;
overload directive must be before virtual, not after.

Same for **lines 891 and 937**.

**Comment by joaopauloschuler** [comment]
HuguesDug, thank you.

**Comment by HuguesDug** [comment]
Hello,

Your welcome ;-)

After last change, it still does not work : you forgot to apply the same change for lines 891 and 937.
Here as well you need to swap overload and virtual declarations.

**Comment by joaopauloschuler** [comment]
Sorry for that and thank you again!

**Comment by HuguesDug** [comment]
No problem.
Tested the release of 2 hours ago. No more problems.

However, a significant load of "warnings" with variable unused or set without any need. Should be worth a look. I some case, I think you might have done things... that are at the end not used. Strange.

[dcc64 Avertissement] neuralvolume.pas(389): W1055 PUBLISHED a provoqué l'ajout de RTTI ($M+) au type 'TMObject'
[dcc64 Avertissement] neuralvolume.pas(450): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TMObject'
[dcc64 Avertissement] neuralbit.pas(928): W1011 Texte après le 'END' final. - ignoré par le compilateur
[dcc64 Avertissement] neuralvolume.pas(2348): W1036 La variable 'x' n'a pas été initialisée
[dcc64 Conseil] neuralvolume.pas(4493): H2077 La valeur affectée à 'version' n'est jamais utilisée
[dcc64 Conseil] neuralvolume.pas(4490): H2077 La valeur affectée à 'version' n'est jamais utilisée
[dcc64 Conseil] neuralvolume.pas(4718): H2077 La valeur affectée à 'MissedElements' n'est jamais utilisée
[dcc64 Conseil] neuralvolume.pas(4706): H2164 La variable 'CntAPos' est déclarée mais jamais utilisée dans 'TNNetVolume.DotProducts'
[dcc64 Conseil] neuralvolume.pas(4706): H2164 La variable 'CntBPos' est déclarée mais jamais utilisée dans 'TNNetVolume.DotProducts'
[dcc64 Conseil] neuralvolume.pas(4707): H2164 La variable 'DestPointer' est déclarée mais jamais utilisée dans 'TNNetVolume.DotProducts'
[dcc64 Conseil] neuralvolume.pas(4708): H2164 La variable 'CntBVectorSizePlusCntBPos' est déclarée mais jamais utilisée dans 'TNNetVolume.DotProducts'
[dcc64 Conseil] neuralvolume.pas(4709): H2164 La variable 'vRes' est déclarée mais jamais utilisée dans 'TNNetVolume.DotProducts'
[dcc64 Avertissement] neuralvolume.pas(8264): W1029 constructor 'TNNetVolumePair.CreateCopying' en double avec des paramètres identiques inaccessible dans C++
[dcc64 Avertissement] neuralnetwork.pas(331): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayer'
[dcc64 Avertissement] neuralnetwork.pas(332): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayer'
[dcc64 Avertissement] neuralnetwork.pas(333): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayer'
[dcc64 Avertissement] neuralnetwork.pas(357): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayer'
[dcc64 Avertissement] neuralnetwork.pas(398): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayer'
[dcc64 Avertissement] neuralnetwork.pas(426): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayer'
[dcc64 Avertissement] neuralnetwork.pas(468): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayer'
[dcc64 Avertissement] neuralnetwork.pas(475): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayer'
[dcc64 Avertissement] neuralnetwork.pas(495): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayer'
[dcc64 Avertissement] neuralnetwork.pas(512): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayer'
[dcc64 Avertissement] neuralnetwork.pas(523): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayer'
[dcc64 Avertissement] neuralnetwork.pas(647): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayer'
[dcc64 Avertissement] neuralnetwork.pas(666): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayer'
[dcc64 Avertissement] neuralnetwork.pas(692): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetConcatBase'
[dcc64 Avertissement] neuralnetwork.pas(693): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetConcatBase'
[dcc64 Avertissement] neuralnetwork.pas(707): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetConcatBase'
[dcc64 Avertissement] neuralnetwork.pas(717): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetConcatBase'
[dcc64 Avertissement] neuralnetwork.pas(730): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayer'
[dcc64 Avertissement] neuralnetwork.pas(731): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayer'
[dcc64 Avertissement] neuralnetwork.pas(755): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayerConcatedWeights'
[dcc64 Avertissement] neuralnetwork.pas(756): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayerConcatedWeights'
[dcc64 Avertissement] neuralnetwork.pas(841): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayerConcatedWeights'
[dcc64 Avertissement] neuralnetwork.pas(1041): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TNNetLayer'
[dcc64 Conseil] neuralnetwork.pas(1838): H2077 La valeur affectée à 'InputCntX' n'est jamais utilisée
[dcc64 Conseil] neuralnetwork.pas(1835): H2077 La valeur affectée à 'InputCntY' n'est jamais utilisée
[dcc64 Conseil] neuralnetwork.pas(1833): H2077 La valeur affectée à 'CntXYD' n'est jamais utilisée
[dcc64 Conseil] neuralnetwork.pas(1818): H2077 La valeur affectée à 'InputCntY' n'est jamais utilisée
[dcc64 Conseil] neuralnetwork.pas(1815): H2077 La valeur affectée à 'CntXYD' n'est jamais utilisée
[dcc64 Conseil] neuralnetwork.pas(1813): H2077 La valeur affectée à 'InputCntX' n'est jamais utilisée
[dcc64 Conseil] neuralnetwork.pas(6097): H2077 La valeur affectée à 'Len' n'est jamais utilisée
[dcc64 Conseil] neuralnetwork.pas(6291): H2077 La valeur affectée à 'InputCntX' n'est jamais utilisée
[dcc64 Conseil] neuralnetwork.pas(6288): H2077 La valeur affectée à 'InputCntY' n'est jamais utilisée
[dcc64 Conseil] neuralnetwork.pas(6286): H2077 La valeur affectée à 'CntXYD' n'est jamais utilisée
[dcc64 Conseil] neuralnetwork.pas(6268): H2077 La valeur affectée à 'InputCntY' n'est jamais utilisée
[dcc64 Conseil] neuralnetwork.pas(6265): H2077 La valeur affectée à 'CntXYD' n'est jamais utilisée
[dcc64 Conseil] neuralnetwork.pas(6263): H2077 La valeur affectée à 'InputCntX' n'est jamais utilisée
[dcc64 Conseil] neuralnetwork.pas(6979): H2077 La valeur affectée à 'RowSize' n'est jamais utilisée
[dcc64 Conseil] neuralnetwork.pas(7212): H2077 La valeur affectée à 'SmoothLocalOutputErrorDerivPtr' n'est jamais utilisée
[dcc64 Avertissement] neuralnetwork.pas(7387): W1036 La variable 'LocalDestPtr' n'a pas été initialisée
[dcc64 Conseil] neuralnetwork.pas(7194): H2164 La variable 'PtrNeuronDelta' est déclarée mais jamais utilisée dans 'TNNetConvolution.BackpropagateFastCPU'
[dcc64 Conseil] neuralnetwork.pas(7502): H2077 La valeur affectée à 'PtrPreparedInput' n'est jamais utilisée
[dcc64 Avertissement] neuralnetwork.pas(7555): W1036 La variable 'LocalDestPtr' n'a pas été initialisée
[dcc64 Conseil] neuralnetwork.pas(7468): H2164 La variable 'PtrNeuronDelta' est déclarée mais jamais utilisée dans 'TNNetConvolution.BackpropagateFastCPUDev'
[dcc64 Conseil] neuralnetwork.pas(850): H2219 Le symbole privé 'BackpropagateCPU' est déclaré mais jamais utilisé
[dcc64 Conseil] neuralnetwork.pas(853): H2219 Le symbole privé 'ComputeCPU' est déclaré mais jamais utilisé
[dcc64 Conseil] neuralnetwork.pas(884): H2219 Le symbole privé 'PrepareInputForConvolution' est déclaré mais jamais utilisé
[dcc64 Conseil] neuralnetwork.pas(914): H2219 Le symbole privé 'ComputeNeuronCPU' est déclaré mais jamais utilisé
[dcc64 Conseil] neuralnetwork.pas(915): H2219 Le symbole privé 'AddBiasToRawResult' est déclaré mais jamais utilisé
[dcc64 Conseil] neuralnetwork.pas(917): H2219 Le symbole privé 'ComputeNeuron' est déclaré mais jamais utilisé
[dcc64 Conseil] neuralnetwork.pas(919): H2219 Le symbole privé 'ComputeNeuronAtOutputPos3' est déclaré mais jamais utilisé
[dcc64 Conseil] neuralnetwork.pas(920): H2219 Le symbole privé 'ComputeNeuronAtOutputPos3D3' est déclaré mais jamais utilisé
[dcc64 Conseil] neuralnetwork.pas(921): H2219 Le symbole privé 'ComputeNeuronAtOutputPosDefault' est déclaré mais jamais utilisé
[dcc64 Conseil] neuralnetwork.pas(922): H2219 Le symbole privé 'ComputeNeuronAtOutputPosDefaultFast' est déclaré mais jamais utilisé
[dcc64 Avertissement] neuralfit.pas(94): W1010 La méthode 'Create' cache une méthode virtuelle de type de base 'TMObject'
[dcc64 Conseil] neuralfit.pas(993): H2077 La valeur affectée à 'MaxDelta' n'est jamais utilisée
[dcc64 Conseil] neuralfit.pas(1352): H2077 La valeur affectée à 'MaxDelta' n'est jamais utilisée

**Comment by joaopauloschuler** [comment]
Thank you for bringing to my attention warnings that you see at your environment.

Some of the warning are interesting such as "neuralnetwork.pas(1818): H2077 La valeur affectée à 'InputCntY' n'est jamais utilisée". 

Some warnings are platform specific such as "neuralnetwork.pas(6979): H2077 La valeur affectée à 'RowSize' n'est jamais utilisée".  **RowSize** is actually used in neuralasm.inc with "mov ecx, RowSize".

I'll work on this eventually.

**Comment by joaopauloschuler** [comment]
Just created a new issue for this: https://github.com/joaopauloschuler/neural-api/issues/40
