### ISSUE TITLE
Could not compile used unit 'neuralfit.pas' - Delphi 10.4.2

### ISSUE THREAD

**Issue by laurenceliew** [joaopauloschuler/neural-api#55]
Hi,
I am trying to compile and run the SimpleMNist demo in Delphi 10.4.2 in Windows 64-bit.

I get the following error:

Message:
[dcc64 Error] neuralfit.pas(1354): E2036 Variable required
[dcc64 Fatal Error] SimpleMNist.dpr(13): F2063 Could not compile used unit 'neuralfit.pas'

The error in neralfit source:

procedure TNeuralDataLoadingFit.EnableDefaultImageTreatment();
begin
  inherited EnableDefaultImageTreatment();
  EnableClassComparison();
  FLossFn := @DefaultLossFn;   <-------- E2036 Variable required.
end;

Thanks if you have any hints.

10.4.2 has the latest patches applied earlier today and all settings are default.

**Comment by joaopauloschuler** [comment]
Thank you for reporting. I can reproduce it at my end.

**Comment by joaopauloschuler** [comment]
@laurenceliew , please confirm it the fix works.

**Comment by laurenceliew** [comment]
Hi @joaopauloschuler 

Thanks - neuralfit.pas compiles now with no issues.

Thanks!
