### ISSUE TITLE
Error execute with new version and Delphi 10.3

### ISSUE THREAD

**Issue by JeanYvesJonet** [joaopauloschuler/neural-api#68]
Hello,
after the problem with TNNet class missing, i have a new problem when I execute a code without problem with old version.
Classe d'exception Exception avec un message 'TNNetInput:32;32;1;0;0;0;0;0 not allowed in CreateLayer
Thanks

**Comment by joaopauloschuler** [comment]
@JeanYvesJonet , does this commit fix?

**Comment by joaopauloschuler** [comment]
Glad to help!
