### ISSUE TITLE
examples VisualGAN

### ISSUE THREAD

**Issue by magicse** [joaopauloschuler/neural-api#95]
When compiling example VisaulGAN (Lazarus) I get next error - 
uvisualgan.pas(326,5) Error: Wrong number of parameters specified for call to "Create"
neuralnetwork.pas(3093,24) Error: Found declaration: constructor Create(LongInt;LongInt;LongInt);

**Comment by joaopauloschuler** [comment]
@magicse, thank you for the report. I can reproduce it. I'll fix in the next version.

**Comment by joaopauloschuler** [comment]
@magicse ,
You can search for `TNNetReLUL.Create(-40, +40) // Protection against overflow` and then replace by `TNNetReLUL.Create(-40, +40, 0) // Protection against overflow` 

This will solve the problem.
