### ISSUE TITLE
HTML support 

I need to create a page that after some minutes load another html file.

Can you help?

### ISSUE THREAD

**Issue by Slyingme** [joaopauloschuler/neural-api#97]
`<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

/* Criar duas colunas frutuantes proximas uma a outra */
.column {
  float: left;
  padding: 10px;
  height: 620px; 
}

.left {
  width: 80%;
}

.right {
  width: 20%;
}

/* Limpar os Flutuantes após criar as colunas */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/*Barra de carregamento*/
.progress{
    height: 15px;
    background-color: #777;
    position: relative;
}
.progress .progress-bar{
   position: absolute;
   height: 100%;
   background-color: #00AA00;
   animation: progress-animation 90s infinite;
}
@keyframes progress-animation{
    0% { width: 0%; }
    100% { width: 100%}
}
</style>
<meta http-equiv="refresh" content="90" >
</head>
<body>

<div class="row">
  <div class="column left" style="background-color:#FFFFFF;">
	/*This frame should automatically change to anothet  html file when a countdown  finishes*/
    <IFRAME src="K:\DEPTOS\EXPEDICAO\Gabriel\Projetos\01 - LEVANTAMENTOS\MONITOR 2023.htm" width=100% height=100% scrolling="no" frameborder="0" align="LEFT"></IFRAME>
  </div>
  <div class="column right" style="background-color:#EEEEEE;"meta http-equiv="refresh" content="15", >
  
	<IFRAME src="\\SRVMBR08V\FILES\DEPTOS\EXPEDICAO\07 INDICADORES\META 2020\agenda comex.htm" width=100% height=100% scrolling="no" frameborder="0" align="LEFT"></IFRAME>
	</div>
</div>
	<div class="progress" style="background-color:#FFFFFF;">
		<font color = #000000 >Proxima atualização: </font>
		<div class="progress-bar"></div>
	</div>	
</body>
</html>
`

**Comment by joaopauloschuler** [comment]
Your request is unrelated to this API.
